project:
  type: website
  output-dir: docs

website:
  title: "Quandong Pan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: resources.qmd
        text: Resources
      #href: my-blog.qmd
      #text: Welcome to My Blog!
      - href: CV.qmd
        text: Curriculum Vitae


format:
  html:
    theme: Lux
    css: styles.css
    toc: true
    page-layout: full

editor: visual

